src/Entity/ProductType.php
<?php

namespace App\Entity;

use App\Repository\ProductTypeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductTypeRepository::class)
 */
class ProductType
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_product;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduct(): ?int
    {
        return $this->id_product;
    }

    public function setIdProduct(int $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Specialty.php
<?php

namespace App\Entity;

use App\Repository\SpecialtyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SpecialtyRepository::class)
 */
class Specialty
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_customer;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Establishment::class, inversedBy="likes")
     */
    private $establishment_link;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCustomer(): ?int
    {
        return $this->id_customer;
    }

    public function setIdCustomer(int $id_customer): self
    {
        $this->id_customer = $id_customer;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getEstablishmentLink(): ?Establishment
    {
        return $this->establishment_link;
    }

    public function setEstablishmentLink(?Establishment $establishment_link): self
    {
        $this->establishment_link = $establishment_link;

        return $this;
    }
}

templates/establishment_staff_admin/_delete_form.html.twig
<form method="post" action="{{ path('establishment_staff_admin_delete', {'id': establishment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ establishment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/establishment_staff_admin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/establishment_staff_admin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Establishment{% endblock %}

{% block body %}
    <h1>Edit Establishment</h1>

    {{ include('establishment_staff_admin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('establishment_staff_admin_index') }}">back to list</a>

    {{ include('establishment_staff_admin/_delete_form.html.twig') }}
{% endblock %}

templates/establishment_staff_admin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Establishment index{% endblock %}

{% block body %}
    <h1>Establishment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_customer</th>
                <th>Type</th>
                <th>Description</th>
                <th>Price_range</th>
                <th>Id_product</th>
                <th>Facebook</th>
                <th>Instagram</th>
                <th>Twitter</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for establishment in establishments %}
            <tr>
                <td>{{ establishment.id }}</td>
                <td>{{ establishment.idCustomer }}</td>
                <td>{{ establishment.type }}</td>
                <td>{{ establishment.description }}</td>
                <td>{{ establishment.priceRange }}</td>
                <td>{{ establishment.idProduct }}</td>
                <td>{{ establishment.facebook }}</td>
                <td>{{ establishment.instagram }}</td>
                <td>{{ establishment.twitter }}</td>
                <td>
                    <a href="{{ path('establishment_staff_admin_show', {'id': establishment.id}) }}">show</a>
                    <a href="{{ path('establishment_staff_admin_edit', {'id': establishment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('establishment_staff_admin_new') }}">Create new</a>
{% endblock %}

templates/establishment_staff_admin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Establishment{% endblock %}

{% block body %}
    <h1>Create new Establishment</h1>

    {{ include('establishment_staff_admin/_form.html.twig') }}

    <a href="{{ path('establishment_staff_admin_index') }}">back to list</a>
{% endblock %}

templates/establishment_staff_admin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Establishment{% endblock %}

{% block body %}
    <h1>Establishment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ establishment.id }}</td>
            </tr>
            <tr>
                <th>Id_customer</th>
                <td>{{ establishment.idCustomer }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ establishment.type }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ establishment.description }}</td>
            </tr>
            <tr>
                <th>Price_range</th>
                <td>{{ establishment.priceRange }}</td>
            </tr>
            <tr>
                <th>Id_product</th>
                <td>{{ establishment.idProduct }}</td>
            </tr>
            <tr>
                <th>Facebook</th>
                <td>{{ establishment.facebook }}</td>
            </tr>
            <tr>
                <th>Instagram</th>
                <td>{{ establishment.instagram }}</td>
            </tr>
            <tr>
                <th>Twitter</th>
                <td>{{ establishment.twitter }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('establishment_staff_admin_index') }}">back to list</a>

    <a href="{{ path('establishment_staff_admin_edit', {'id': establishment.id}) }}">edit</a>

    {{ include('establishment_staff_admin/_delete_form.html.twig') }}
{% endblock %}